Fix docs diff CI job (#264)
We were not failing the job if new files should have been present but
were not.

diff --git a/.github/workflows/docs-diff.yaml b/.github/workflows/docs-diff.yaml
--- a/.github/workflows/docs-diff.yaml
+++ b/.github/workflows/docs-diff.yaml
@@ -24,5 +24,16 @@ jobs:
       - run: go version
       - run: terraform version
       - run: make docs
-      - run: git diff --exit-code
+      - run: |
+          set -euo pipefail
 
+          echo "Checking all doc files are in sync with checked-in"
+          status="$(git status --short)"
+          if [[ ! -z $status ]]
+          then
+              echo "some doc files are out of sync or missing"
+              echo "run `make docs` and commit the changes"
+              echo "$status"
+              exit 1
+          fi
+          echo "Input and generated seem up-to-date"
